using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace LinqContraband.Catalog;

public static partial class RuleCatalog
{
    private static ImmutableArray<RuleCatalogEntry> CreateLC031ToLC045Entries()
    {
        return ImmutableArray.Create(
            new RuleCatalogEntry(
                id: "LC031",
                slug: "LC031_UnboundedQueryMaterialization",
                title: "Unbounded Query Materialization",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "UnboundedQueryMaterializationAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC031_UnboundedQueryMaterialization.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC031_UnboundedQueryMaterialization/UnboundedQueryMaterializationSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC031_UnboundedQueryMaterialization",
                hasCodeFix: false,
                noCodeFixRationale: "No universally correct fix: the caller must decide the appropriate filter, Take limit, pagination strategy, or intentional full scan."),
            new RuleCatalogEntry(
                id: "LC032",
                slug: "LC032_ExecuteUpdateForBulkUpdates",
                title: "Use ExecuteUpdate for provable bulk scalar updates",
                category: "Performance",
                domain: "Bulk Operations & Set-Based Writes",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "ExecuteUpdateForBulkUpdatesAnalyzer",
                fixerTypeName: "ExecuteUpdateForBulkUpdatesFixer",
                documentationPath: "docs/LC032_ExecuteUpdateForBulkUpdates.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC032_ExecuteUpdateForBulkUpdates/ExecuteUpdateForBulkUpdatesSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/BulkOperationsAndSetBasedWrites/LC032_ExecuteUpdateForBulkUpdates",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC033",
                slug: "LC033_UseFrozenSetForStaticMembershipCaches",
                title: "Use FrozenSet for provably read-only membership caches",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "UseFrozenSetForStaticMembershipCachesAnalyzer",
                fixerTypeName: "UseFrozenSetForStaticMembershipCachesFixer",
                documentationPath: "docs/LC033_UseFrozenSetForStaticMembershipCaches.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC033_UseFrozenSetForStaticMembershipCaches/UseFrozenSetForStaticMembershipCachesSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC033_UseFrozenSetForStaticMembershipCaches",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC034",
                slug: "LC034_AvoidExecuteSqlRawWithInterpolation",
                title: "Avoid ExecuteSqlRaw with interpolated strings",
                category: "Security",
                domain: "Raw SQL & Security",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AvoidExecuteSqlRawWithInterpolationAnalyzer",
                fixerTypeName: "AvoidExecuteSqlRawWithInterpolationFixer",
                documentationPath: "docs/LC034_AvoidExecuteSqlRawWithInterpolation.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC034_AvoidExecuteSqlRawWithInterpolation/ExecuteSqlRawInterpolationSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/RawSqlAndSecurity/LC034_AvoidExecuteSqlRawWithInterpolation",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC035",
                slug: "LC035_MissingWhereBeforeExecuteDeleteUpdate",
                title: "Missing Where before bulk execute",
                category: "Safety",
                domain: "Bulk Operations & Set-Based Writes",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MissingWhereBeforeExecuteDeleteUpdateAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC035_MissingWhereBeforeExecuteDeleteUpdate.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC035_MissingWhereBeforeExecuteDeleteUpdate/MissingWhereBeforeExecuteDeleteUpdateSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/BulkOperationsAndSetBasedWrites/LC035_MissingWhereBeforeExecuteDeleteUpdate",
                hasCodeFix: false,
                noCodeFixRationale: "No automatic fix: adding a predicate would invent business logic and could silently change data scope."),
            new RuleCatalogEntry(
                id: "LC036",
                slug: "LC036_DbContextCapturedAcrossThreads",
                title: "DbContext captured by thread work item",
                category: "Safety",
                domain: "Execution & Async",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "DbContextCapturedAcrossThreadsAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC036_DbContextCapturedAcrossThreads.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC036_DbContextCapturedAcrossThreads/DbContextCapturedAcrossThreadsSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ExecutionAndAsync/LC036_DbContextCapturedAcrossThreads",
                hasCodeFix: false,
                noCodeFixRationale: "No safe automated rewrite: the correct fix depends on choosing scopes, factories, or asynchronous control flow for the specific workload."),
            new RuleCatalogEntry(
                id: "LC037",
                slug: "LC037_RawSqlStringConstruction",
                title: "Avoid constructed raw SQL strings",
                category: "Security",
                domain: "Raw SQL & Security",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "RawSqlStringConstructionAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC037_RawSqlStringConstruction.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC037_RawSqlStringConstruction/RawSqlStringConstructionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/RawSqlAndSecurity/LC037_RawSqlStringConstruction",
                hasCodeFix: false,
                noCodeFixRationale: "No one-size-fits-all fix: parameterization, interpolated SQL APIs, or query reshaping depend on how the SQL is assembled."),
            new RuleCatalogEntry(
                id: "LC038",
                slug: "LC038_ExcessiveEagerLoading",
                title: "Avoid excessive eager loading",
                category: "Performance",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "ExcessiveEagerLoadingAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC038_ExcessiveEagerLoading.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC038_ExcessiveEagerLoading/ExcessiveEagerLoadingSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC038_ExcessiveEagerLoading",
                hasCodeFix: false,
                noCodeFixRationale: "No automatic fix: trimming includes requires understanding which navigations are actually needed by the caller."),
            new RuleCatalogEntry(
                id: "LC039",
                slug: "LC039_NestedSaveChanges",
                title: "Avoid repeated SaveChanges on the same context",
                category: "Reliability",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "NestedSaveChangesAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC039_NestedSaveChanges.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC039_NestedSaveChanges/NestedSaveChangesSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC039_NestedSaveChanges",
                hasCodeFix: false,
                noCodeFixRationale: "No safe rewrite: batching or transaction reshaping must respect domain ordering, side effects, and error handling."),
            new RuleCatalogEntry(
                id: "LC040",
                slug: "LC040_MixedTrackingAndNoTracking",
                title: "Avoid mixing tracking modes on the same context",
                category: "Reliability",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MixedTrackingAndNoTrackingAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC040_MixedTrackingAndNoTracking.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC040_MixedTrackingAndNoTracking/MixedTrackingAndNoTrackingSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC040_MixedTrackingAndNoTracking",
                hasCodeFix: false,
                noCodeFixRationale: "No automatic fix: the right resolution depends on whether the workflow should be fully tracked, fully read-only, or split across contexts."),
            new RuleCatalogEntry(
                id: "LC041",
                slug: "LC041_SingleEntityScalarProjection",
                title: "Single entity query over-fetches one consumed property",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "SingleEntityScalarProjectionAnalyzer",
                fixerTypeName: "SingleEntityScalarProjectionFixer",
                documentationPath: "docs/LC041_SingleEntityScalarProjection.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC041_SingleEntityScalarProjection/SingleEntityScalarProjectionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC041_SingleEntityScalarProjection",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC042",
                slug: "LC042_MissingQueryTags",
                title: "Complex query should be tagged",
                category: "Performance",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MissingQueryTagsAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC042_MissingQueryTags.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC042_MissingQueryTags/MissingQueryTagsSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC042_MissingQueryTags",
                hasCodeFix: false,
                noCodeFixRationale: "No default fix: teams need to decide the tagging convention and tag text that fit their observability standards."),
            new RuleCatalogEntry(
                id: "LC043",
                slug: "LC043_AsyncEnumerableBuffering",
                title: "Prefer await foreach over buffering async streams",
                category: "Performance",
                domain: "Execution & Async",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "AsyncEnumerableBufferingAnalyzer",
                fixerTypeName: "AsyncEnumerableBufferingFixer",
                documentationPath: "docs/LC043_AsyncEnumerableBuffering.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC043_AsyncEnumerableBuffering/AsyncEnumerableBufferingSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ExecutionAndAsync/LC043_AsyncEnumerableBuffering",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC044",
                slug: "LC044_AsNoTrackingThenModify",
                title: "AsNoTracking query mutated then SaveChanges — silent data loss",
                category: "Reliability",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AsNoTrackingThenModifyAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC044_AsNoTrackingThenModifySilentWrite.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC044_AsNoTrackingThenModify/AsNoTrackingThenModifySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC044_AsNoTrackingThenModify",
                hasCodeFix: false,
                noCodeFixRationale: "No automatic fix: the right resolution depends on intent — either remove AsNoTracking() so the entity is tracked from origin, or call Update/Attach (or set Entry.State = Modified) before SaveChanges. Both are semantically valid depending on context."),
            new RuleCatalogEntry(
                id: "LC045",
                slug: "LC045_MissingInclude",
                title: "Missing Include: navigation accessed on materialized entity",
                category: "Reliability",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "MissingIncludeAnalyzer",
                fixerTypeName: "MissingIncludeFixer",
                documentationPath: "docs/LC045_MissingInclude.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC045_MissingInclude/MissingIncludeSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC045_MissingInclude",
                hasCodeFix: true,
                noCodeFixRationale: null));
    }
}
