using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace LinqContraband.Catalog;

public static partial class RuleCatalog
{
    private static ImmutableArray<RuleCatalogEntry> CreateLC001ToLC015Entries()
    {
        return ImmutableArray.Create(
            new RuleCatalogEntry(
                id: "LC001",
                slug: "LC001_LocalMethod",
                title: "Client-side evaluation risk: Local method usage in IQueryable",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "LocalMethodAnalyzer",
                fixerTypeName: "LocalMethodFixer",
                documentationPath: "docs/LC001_LocalMethod.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC001_LocalMethod/LocalMethodSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC001_LocalMethod",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC002",
                slug: "LC002_PrematureMaterialization",
                title: "Premature query continuation after materialization",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "PrematureMaterializationAnalyzer",
                fixerTypeName: "PrematureMaterializationFixer",
                documentationPath: "docs/LC002_PrematureMaterialization.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC002_PrematureMaterialization/PrematureMaterializationSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC002_PrematureMaterialization",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC003",
                slug: "LC003_AnyOverCount",
                title: "Prefer Any() over Count() existence checks",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AnyOverCountAnalyzer",
                fixerTypeName: "AnyOverCountFixer",
                documentationPath: "docs/LC003_AnyOverCount.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC003_AnyOverCount/AnyOverCountSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC003_AnyOverCount",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC004",
                slug: "LC004_IQueryableLeak",
                title: "Deferred Execution Leak: IQueryable passed as IEnumerable",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "IQueryableLeakAnalyzer",
                fixerTypeName: "IQueryableLeakFixer",
                documentationPath: "docs/LC004_IQueryableLeak.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC004_IQueryableLeak/IQueryableLeakSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC004_IQueryableLeak",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC005",
                slug: "LC005_MultipleOrderBy",
                title: "Multiple OrderBy calls",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "MultipleOrderByAnalyzer",
                fixerTypeName: "MultipleOrderByFixer",
                documentationPath: "docs/LC005_MultipleOrderBy.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC005_MultipleOrderBy/MultipleOrderBySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC005_MultipleOrderBy",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC006",
                slug: "LC006_CartesianExplosion",
                title: "Cartesian Explosion Risk: Multiple Collection Includes",
                category: "Performance",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "CartesianExplosionAnalyzer",
                fixerTypeName: "CartesianExplosionFixer",
                documentationPath: "docs/LC006_CartesianExplosion.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC006_CartesianExplosion/CartesianExplosionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC006_CartesianExplosion",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC007",
                slug: "LC007_NPlusOneLooper",
                title: "N+1 Problem: Database execution inside loop",
                category: "Performance",
                domain: "Execution & Async",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "NPlusOneLooperAnalyzer",
                fixerTypeName: "NPlusOneLooperFixer",
                documentationPath: "docs/LC007_NPlusOneLooper.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC007_NPlusOneLooper/NPlusOneLooperSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ExecutionAndAsync/LC007_NPlusOneLooper",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC008",
                slug: "LC008_SyncBlocker",
                title: "Sync-over-Async: Synchronous EF Core method in Async context",
                category: "Performance",
                domain: "Execution & Async",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "SyncBlockerAnalyzer",
                fixerTypeName: "SyncBlockerFixer",
                documentationPath: "docs/LC008_SyncBlocker.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC008_SyncBlocker/SyncBlockerSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ExecutionAndAsync/LC008_SyncBlocker",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC009",
                slug: "LC009_MissingAsNoTracking",
                title: "Performance: Missing AsNoTracking() in Read-Only path",
                category: "Performance",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MissingAsNoTrackingAnalyzer",
                fixerTypeName: "MissingAsNoTrackingFixer",
                documentationPath: "docs/LC009_MissingAsNoTracking.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC009_MissingAsNoTracking/MissingAsNoTrackingSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC009_MissingAsNoTracking",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC010",
                slug: "LC010_SaveChangesInLoop",
                title: "N+1 Write Problem: SaveChanges inside loop",
                category: "Performance",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "SaveChangesInLoopAnalyzer",
                fixerTypeName: "SaveChangesInLoopFixer",
                documentationPath: "docs/LC010_SaveChangesInLoop.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC010_SaveChangesInLoop/SaveChangesInLoopSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC010_SaveChangesInLoop",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC011",
                slug: "LC011_EntityMissingPrimaryKey",
                title: "Design: Entity missing Primary Key",
                category: "Design",
                domain: "Schema & Modeling",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "EntityMissingPrimaryKeyAnalyzer",
                fixerTypeName: "EntityMissingPrimaryKeyFixer",
                documentationPath: "docs/LC011_EntityMissingPrimaryKey.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC011_EntityMissingPrimaryKey/EntityMissingPrimaryKeySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/SchemaAndModeling/LC011_EntityMissingPrimaryKey",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC012",
                slug: "LC012_OptimizeRemoveRange",
                title: "Optimize: Use ExecuteDelete() instead of RemoveRange()",
                category: "Performance",
                domain: "Bulk Operations & Set-Based Writes",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "OptimizeRemoveRangeAnalyzer",
                fixerTypeName: "OptimizeRemoveRangeFixer",
                documentationPath: "docs/LC012_OptimizeRemoveRange.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC012_OptimizeRemoveRange/OptimizeRemoveRangeSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/BulkOperationsAndSetBasedWrites/LC012_OptimizeRemoveRange",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC013",
                slug: "LC013_DisposedContextQuery",
                title: "Disposed Context Query",
                category: "Reliability",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "DisposedContextQueryAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC013_DisposedContextQuery.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC013_DisposedContextQuery/DisposedContextQuerySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC013_DisposedContextQuery",
                hasCodeFix: false,
                noCodeFixRationale: "No safe automated rewrite: the fix depends on reshaping DbContext lifetime and query ownership."),
            new RuleCatalogEntry(
                id: "LC014",
                slug: "LC014_AvoidStringCaseConversion",
                title: "Avoid String.ToLower() or ToUpper() in LINQ queries",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AvoidStringCaseConversionAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC014_AvoidStringCaseConversion.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC014_AvoidStringCaseConversion/AvoidStringCaseConversionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC014_AvoidStringCaseConversion",
                hasCodeFix: false,
                noCodeFixRationale: "No safe automated rewrite: case-insensitive comparison depends on database collation, provider translation support, and available indexes."),
            new RuleCatalogEntry(
                id: "LC015",
                slug: "LC015_MissingOrderBy",
                title: "Deterministic Pagination: OrderBy required before Skip/Take",
                category: "Reliability",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "MissingOrderByAnalyzer",
                fixerTypeName: "MissingOrderByFixer",
                documentationPath: "docs/LC015_MissingOrderBy.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC015_MissingOrderBy/MissingOrderBySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC015_MissingOrderBy",
                hasCodeFix: true,
                noCodeFixRationale: null)
        );
    }
}
