using System;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace LinqContraband.Catalog;

public static class RuleCatalog
{
    public static ImmutableArray<RuleCatalogEntry> All { get; } = ImmutableArray.Create(
        new RuleCatalogEntry(
            id: "LC001",
            slug: "LC001_LocalMethod",
            title: "Client-side evaluation risk: Local method usage in IQueryable",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "LocalMethodAnalyzer",
            fixerTypeName: "LocalMethodFixer",
            documentationPath: "docs/LC001_LocalMethod.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC001_LocalMethod/LocalMethodSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC002",
            slug: "LC002_PrematureMaterialization",
            title: "Premature query continuation after materialization",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "PrematureMaterializationAnalyzer",
            fixerTypeName: "PrematureMaterializationFixer",
            documentationPath: "docs/LC002_PrematureMaterialization.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC002_PrematureMaterialization/PrematureMaterializationSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC003",
            slug: "LC003_AnyOverCount",
            title: "Prefer Any() over Count() existence checks",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AnyOverCountAnalyzer",
            fixerTypeName: "AnyOverCountFixer",
            documentationPath: "docs/LC003_AnyOverCount.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC003_AnyOverCount/AnyOverCountSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC004",
            slug: "LC004_IQueryableLeak",
            title: "Deferred Execution Leak: IQueryable passed as IEnumerable",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "IQueryableLeakAnalyzer",
            fixerTypeName: "IQueryableLeakFixer",
            documentationPath: "docs/LC004_IQueryableLeak.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC004_IQueryableLeak/IQueryableLeakSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC005",
            slug: "LC005_MultipleOrderBy",
            title: "Multiple OrderBy calls",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "MultipleOrderByAnalyzer",
            fixerTypeName: "MultipleOrderByFixer",
            documentationPath: "docs/LC005_MultipleOrderBy.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC005_MultipleOrderBy/MultipleOrderBySample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC006",
            slug: "LC006_CartesianExplosion",
            title: "Cartesian Explosion Risk: Multiple Collection Includes",
            category: "Performance",
            domain: "Loading & Includes",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "CartesianExplosionAnalyzer",
            fixerTypeName: "CartesianExplosionFixer",
            documentationPath: "docs/LC006_CartesianExplosion.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC006_CartesianExplosion/CartesianExplosionSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC007",
            slug: "LC007_NPlusOneLooper",
            title: "N+1 Problem: Database execution inside loop",
            category: "Performance",
            domain: "Execution & Async",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "NPlusOneLooperAnalyzer",
            fixerTypeName: "NPlusOneLooperFixer",
            documentationPath: "docs/LC007_NPlusOneLooper.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC007_NPlusOneLooper/NPlusOneLooperSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC008",
            slug: "LC008_SyncBlocker",
            title: "Sync-over-Async: Synchronous EF Core method in Async context",
            category: "Performance",
            domain: "Execution & Async",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "SyncBlockerAnalyzer",
            fixerTypeName: "SyncBlockerFixer",
            documentationPath: "docs/LC008_SyncBlocker.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC008_SyncBlocker/SyncBlockerSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC009",
            slug: "LC009_MissingAsNoTracking",
            title: "Performance: Missing AsNoTracking() in Read-Only path",
            category: "Performance",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MissingAsNoTrackingAnalyzer",
            fixerTypeName: "MissingAsNoTrackingFixer",
            documentationPath: "docs/LC009_MissingAsNoTracking.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC009_MissingAsNoTracking/MissingAsNoTrackingSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC010",
            slug: "LC010_SaveChangesInLoop",
            title: "N+1 Write Problem: SaveChanges inside loop",
            category: "Performance",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "SaveChangesInLoopAnalyzer",
            fixerTypeName: "SaveChangesInLoopFixer",
            documentationPath: "docs/LC010_SaveChangesInLoop.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC010_SaveChangesInLoop/SaveChangesInLoopSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC011",
            slug: "LC011_EntityMissingPrimaryKey",
            title: "Design: Entity missing Primary Key",
            category: "Design",
            domain: "Schema & Modeling",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "EntityMissingPrimaryKeyAnalyzer",
            fixerTypeName: "EntityMissingPrimaryKeyFixer",
            documentationPath: "docs/LC011_EntityMissingPrimaryKey.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC011_EntityMissingPrimaryKey/EntityMissingPrimaryKeySample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC012",
            slug: "LC012_OptimizeRemoveRange",
            title: "Optimize: Use ExecuteDelete() instead of RemoveRange()",
            category: "Performance",
            domain: "Bulk Operations & Set-Based Writes",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "OptimizeRemoveRangeAnalyzer",
            fixerTypeName: "OptimizeRemoveRangeFixer",
            documentationPath: "docs/LC012_OptimizeRemoveRange.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC012_OptimizeRemoveRange/OptimizeRemoveRangeSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC013",
            slug: "LC013_DisposedContextQuery",
            title: "Disposed Context Query",
            category: "Reliability",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "DisposedContextQueryAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC013_DisposedContextQuery.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC013_DisposedContextQuery/DisposedContextQuerySample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe automated rewrite: the fix depends on reshaping DbContext lifetime and query ownership."),
        new RuleCatalogEntry(
            id: "LC014",
            slug: "LC014_AvoidStringCaseConversion",
            title: "Avoid String.ToLower() or ToUpper() in LINQ queries",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AvoidStringCaseConversionAnalyzer",
            fixerTypeName: "AvoidStringCaseConversionFixer",
            documentationPath: "docs/LC014_AvoidStringCaseConversion.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC014_AvoidStringCaseConversion/AvoidStringCaseConversionSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC015",
            slug: "LC015_MissingOrderBy",
            title: "Deterministic Pagination: OrderBy required before Skip/Take",
            category: "Reliability",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "MissingOrderByAnalyzer",
            fixerTypeName: "MissingOrderByFixer",
            documentationPath: "docs/LC015_MissingOrderBy.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC015_MissingOrderBy/MissingOrderBySample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC016",
            slug: "LC016_AvoidDateTimeNow",
            title: "Avoid DateTime.Now/UtcNow in LINQ queries",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AvoidDateTimeNowAnalyzer",
            fixerTypeName: "AvoidDateTimeNowFixer",
            documentationPath: "docs/LC016_AvoidDateTimeNow.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC016_AvoidDateTimeNow/AvoidDateTimeNowSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC017",
            slug: "LC017_WholeEntityProjection",
            title: "Performance: Consider using Select() projection",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "WholeEntityProjectionAnalyzer",
            fixerTypeName: "WholeEntityProjectionFixer",
            documentationPath: "docs/LC017_WholeEntityProjection.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC017_WholeEntityProjection/WholeEntityProjectionSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC018",
            slug: "LC018_AvoidFromSqlRawWithInterpolation",
            title: "Avoid FromSqlRaw with interpolated strings",
            category: "Security",
            domain: "Raw SQL & Security",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AvoidFromSqlRawWithInterpolationAnalyzer",
            fixerTypeName: "AvoidFromSqlRawWithInterpolationFixer",
            documentationPath: "docs/LC018_AvoidFromSqlRawWithInterpolation.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC018_AvoidFromSqlRawWithInterpolation/AvoidFromSqlRawWithInterpolationSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC019",
            slug: "LC019_ConditionalInclude",
            title: "Conditional Include Expression",
            category: "Correctness",
            domain: "Loading & Includes",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "ConditionalIncludeAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC019_ConditionalInclude.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC019_ConditionalInclude/ConditionalIncludeSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No generally correct code fix: callers must choose between splitting queries, reshaping projections, or removing the conditional include path."),
        new RuleCatalogEntry(
            id: "LC020",
            slug: "LC020_StringContainsWithComparison",
            title: "Avoid untranslatable string comparison overloads",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "StringContainsWithComparisonAnalyzer",
            fixerTypeName: "StringContainsWithComparisonFixer",
            documentationPath: "docs/LC020_StringContainsWithComparison.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC020_StringContainsWithComparison/StringContainsWithComparisonSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC021",
            slug: "LC021_AvoidIgnoreQueryFilters",
            title: "Avoid IgnoreQueryFilters",
            category: "Security",
            domain: "Raw SQL & Security",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AvoidIgnoreQueryFiltersAnalyzer",
            fixerTypeName: "AvoidIgnoreQueryFiltersFixer",
            documentationPath: "docs/LC021_AvoidIgnoreQueryFilters.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC021_AvoidIgnoreQueryFilters/AvoidIgnoreQueryFiltersSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC022",
            slug: "LC022_ToListInSelectProjection",
            title: "ToList/ToArray Inside Select Projection",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "ToListInSelectProjectionAnalyzer",
            fixerTypeName: "ToListInSelectProjectionFixer",
            documentationPath: "docs/LC022_ToListInSelectProjection.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC022_ToListInSelectProjection/ToListInSelectProjectionSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC023",
            slug: "LC023_FindInsteadOfFirstOrDefault",
            title: "Use Find/FindAsync for primary key lookups",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "FindInsteadOfFirstOrDefaultAnalyzer",
            fixerTypeName: "FindInsteadOfFirstOrDefaultFixer",
            documentationPath: "docs/LC023_FindInsteadOfFirstOrDefault.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC023_FindInsteadOfFirstOrDefault/FindInsteadOfFirstOrDefaultSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC024",
            slug: "LC024_GroupByNonTranslatable",
            title: "GroupBy with Non-Translatable Projection",
            category: "Performance",
            domain: "Query Shape & Translation",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "GroupByNonTranslatableAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC024_GroupByNonTranslatable.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC024_GroupByNonTranslatable/GroupByNonTranslatableSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe one-click fix: the correct rewrite depends on whether the query should aggregate on the server, project earlier, or materialize intentionally before performing complex grouping in memory."),
        new RuleCatalogEntry(
            id: "LC025",
            slug: "LC025_AsNoTrackingWithUpdate",
            title: "Avoid AsNoTracking with Update/Remove",
            category: "Reliability",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AsNoTrackingWithUpdateAnalyzer",
            fixerTypeName: "AsNoTrackingWithUpdateFixer",
            documentationPath: "docs/LC025_AsNoTrackingWithUpdate.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC025_AsNoTrackingWithUpdate/AsNoTrackingWithUpdateSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC026",
            slug: "LC026_MissingCancellationToken",
            title: "Missing CancellationToken in async call",
            category: "Reliability",
            domain: "Execution & Async",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MissingCancellationTokenAnalyzer",
            fixerTypeName: "MissingCancellationTokenFixer",
            documentationPath: "docs/LC026_MissingCancellationToken.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC026_MissingCancellationToken/MissingCancellationTokenSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC027",
            slug: "LC027_MissingExplicitForeignKey",
            title: "Missing Explicit Foreign Key Property",
            category: "Design",
            domain: "Schema & Modeling",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MissingExplicitForeignKeyAnalyzer",
            fixerTypeName: "MissingExplicitForeignKeyFixer",
            documentationPath: "docs/LC027_MissingExplicitForeignKey.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC027_MissingExplicitForeignKey/MissingExplicitForeignKeySample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC028",
            slug: "LC028_DeepThenInclude",
            title: "Deep ThenInclude Chain",
            category: "Performance",
            domain: "Loading & Includes",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "DeepThenIncludeAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC028_DeepThenInclude.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC028_DeepThenInclude/DeepThenIncludeSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe automated fix: reducing eager-loading depth requires a domain-specific decision about projections, split queries, or alternate loading patterns."),
        new RuleCatalogEntry(
            id: "LC029",
            slug: "LC029_RedundantIdentitySelect",
            title: "Redundant identity Select",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "RedundantIdentitySelectAnalyzer",
            fixerTypeName: "RedundantIdentitySelectFixer",
            documentationPath: "docs/LC029_RedundantIdentitySelect.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC029_RedundantIdentitySelect/RedundantIdentitySelectSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC030",
            slug: "LC030_DbContextInSingleton",
            title: "Potential DbContext lifetime mismatch",
            category: "Architecture",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "DbContextInSingletonAnalyzer",
            fixerTypeName: "DbContextInSingletonFixer",
            documentationPath: "docs/LC030_DbContextInSingleton.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC030_DbContextInSingleton/DbContextInSingletonSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC031",
            slug: "LC031_UnboundedQueryMaterialization",
            title: "Unbounded Query Materialization",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "UnboundedQueryMaterializationAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC031_UnboundedQueryMaterialization.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC031_UnboundedQueryMaterialization/UnboundedQueryMaterializationSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No universally correct fix: the caller must decide the appropriate filter, Take limit, pagination strategy, or intentional full scan."),
        new RuleCatalogEntry(
            id: "LC032",
            slug: "LC032_ExecuteUpdateForBulkUpdates",
            title: "Use ExecuteUpdate for provable bulk scalar updates",
            category: "Performance",
            domain: "Bulk Operations & Set-Based Writes",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "ExecuteUpdateForBulkUpdatesAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC032_ExecuteUpdateForBulkUpdates.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC032_ExecuteUpdateForBulkUpdates/ExecuteUpdateForBulkUpdatesSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe code fix yet: preserving semantics across captured values, concurrency, and provider capabilities requires a conservative manual rewrite."),
        new RuleCatalogEntry(
            id: "LC033",
            slug: "LC033_UseFrozenSetForStaticMembershipCaches",
            title: "Use FrozenSet for provably read-only membership caches",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "UseFrozenSetForStaticMembershipCachesAnalyzer",
            fixerTypeName: "UseFrozenSetForStaticMembershipCachesFixer",
            documentationPath: "docs/LC033_UseFrozenSetForStaticMembershipCaches.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC033_UseFrozenSetForStaticMembershipCaches/UseFrozenSetForStaticMembershipCachesSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC034",
            slug: "LC034_AvoidExecuteSqlRawWithInterpolation",
            title: "Avoid ExecuteSqlRaw with interpolated strings",
            category: "Security",
            domain: "Raw SQL & Security",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "AvoidExecuteSqlRawWithInterpolationAnalyzer",
            fixerTypeName: "AvoidExecuteSqlRawWithInterpolationFixer",
            documentationPath: "docs/LC034_AvoidExecuteSqlRawWithInterpolation.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC034_AvoidExecuteSqlRawWithInterpolation/ExecuteSqlRawInterpolationSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC035",
            slug: "LC035_MissingWhereBeforeExecuteDeleteUpdate",
            title: "Missing Where before bulk execute",
            category: "Safety",
            domain: "Bulk Operations & Set-Based Writes",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MissingWhereBeforeExecuteDeleteUpdateAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC035_MissingWhereBeforeExecuteDeleteUpdate.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC035_MissingWhereBeforeExecuteDeleteUpdate/MissingWhereBeforeExecuteDeleteUpdateSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No automatic fix: adding a predicate would invent business logic and could silently change data scope."),
        new RuleCatalogEntry(
            id: "LC036",
            slug: "LC036_DbContextCapturedAcrossThreads",
            title: "DbContext captured by thread work item",
            category: "Safety",
            domain: "Execution & Async",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "DbContextCapturedAcrossThreadsAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC036_DbContextCapturedAcrossThreads.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC036_DbContextCapturedAcrossThreads/DbContextCapturedAcrossThreadsSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe automated rewrite: the correct fix depends on choosing scopes, factories, or asynchronous control flow for the specific workload."),
        new RuleCatalogEntry(
            id: "LC037",
            slug: "LC037_RawSqlStringConstruction",
            title: "Avoid constructed raw SQL strings",
            category: "Security",
            domain: "Raw SQL & Security",
            severity: DiagnosticSeverity.Warning,
            analyzerTypeName: "RawSqlStringConstructionAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC037_RawSqlStringConstruction.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC037_RawSqlStringConstruction/RawSqlStringConstructionSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No one-size-fits-all fix: parameterization, interpolated SQL APIs, or query reshaping depend on how the SQL is assembled."),
        new RuleCatalogEntry(
            id: "LC038",
            slug: "LC038_ExcessiveEagerLoading",
            title: "Avoid excessive eager loading",
            category: "Performance",
            domain: "Loading & Includes",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "ExcessiveEagerLoadingAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC038_ExcessiveEagerLoading.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC038_ExcessiveEagerLoading/ExcessiveEagerLoadingSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No automatic fix: trimming includes requires understanding which navigations are actually needed by the caller."),
        new RuleCatalogEntry(
            id: "LC039",
            slug: "LC039_NestedSaveChanges",
            title: "Avoid repeated SaveChanges on the same context",
            category: "Reliability",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "NestedSaveChangesAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC039_NestedSaveChanges.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC039_NestedSaveChanges/NestedSaveChangesSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No safe rewrite: batching or transaction reshaping must respect domain ordering, side effects, and error handling."),
        new RuleCatalogEntry(
            id: "LC040",
            slug: "LC040_MixedTrackingAndNoTracking",
            title: "Avoid mixing tracking modes on the same context",
            category: "Reliability",
            domain: "Change Tracking & Context Lifetime",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MixedTrackingAndNoTrackingAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC040_MixedTrackingAndNoTracking.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC040_MixedTrackingAndNoTracking/MixedTrackingAndNoTrackingSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No automatic fix: the right resolution depends on whether the workflow should be fully tracked, fully read-only, or split across contexts."),
        new RuleCatalogEntry(
            id: "LC041",
            slug: "LC041_SingleEntityScalarProjection",
            title: "Single entity query over-fetches one consumed property",
            category: "Performance",
            domain: "Materialization & Projection",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "SingleEntityScalarProjectionAnalyzer",
            fixerTypeName: "SingleEntityScalarProjectionFixer",
            documentationPath: "docs/LC041_SingleEntityScalarProjection.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC041_SingleEntityScalarProjection/SingleEntityScalarProjectionSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null),
        new RuleCatalogEntry(
            id: "LC042",
            slug: "LC042_MissingQueryTags",
            title: "Complex query should be tagged",
            category: "Performance",
            domain: "Loading & Includes",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "MissingQueryTagsAnalyzer",
            fixerTypeName: null,
            documentationPath: "docs/LC042_MissingQueryTags.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC042_MissingQueryTags/MissingQueryTagsSample.cs",
            hasCodeFix: false,
            noCodeFixRationale: "No default fix: teams need to decide the tagging convention and tag text that fit their observability standards."),
        new RuleCatalogEntry(
            id: "LC043",
            slug: "LC043_AsyncEnumerableBuffering",
            title: "Prefer await foreach over buffering async streams",
            category: "Performance",
            domain: "Execution & Async",
            severity: DiagnosticSeverity.Info,
            analyzerTypeName: "AsyncEnumerableBufferingAnalyzer",
            fixerTypeName: "AsyncEnumerableBufferingFixer",
            documentationPath: "docs/LC043_AsyncEnumerableBuffering.md",
            samplePath: "samples/LinqContraband.Sample/Samples/LC043_AsyncEnumerableBuffering/AsyncEnumerableBufferingSample.cs",
            hasCodeFix: true,
            noCodeFixRationale: null)
    );

    public static RuleCatalogEntry GetById(string id)
    {
        foreach (var rule in All)
        {
            if (string.Equals(rule.Id, id, StringComparison.Ordinal))
                return rule;
        }

        throw new ArgumentOutOfRangeException(nameof(id), id, "Unknown LinqContraband rule id.");
    }

    public static ImmutableArray<RuleCatalogEntry> GetByDomain(string domain)
    {
        return All.Where(rule => string.Equals(rule.Domain, domain, StringComparison.Ordinal))
            .OrderBy(rule => rule.Id, StringComparer.Ordinal)
            .ToImmutableArray();
    }
}
