using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace LinqContraband.Catalog;

public static partial class RuleCatalog
{
    private static ImmutableArray<RuleCatalogEntry> CreateLC016ToLC030Entries()
    {
        return ImmutableArray.Create(
            new RuleCatalogEntry(
                id: "LC016",
                slug: "LC016_AvoidDateTimeNow",
                title: "Avoid DateTime.Now/UtcNow in LINQ queries",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AvoidDateTimeNowAnalyzer",
                fixerTypeName: "AvoidDateTimeNowFixer",
                documentationPath: "docs/LC016_AvoidDateTimeNow.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC016_AvoidDateTimeNow/AvoidDateTimeNowSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC016_AvoidDateTimeNow",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC017",
                slug: "LC017_WholeEntityProjection",
                title: "Performance: Consider using Select() projection",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "WholeEntityProjectionAnalyzer",
                fixerTypeName: "WholeEntityProjectionFixer",
                documentationPath: "docs/LC017_WholeEntityProjection.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC017_WholeEntityProjection/WholeEntityProjectionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC017_WholeEntityProjection",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC018",
                slug: "LC018_AvoidFromSqlRawWithInterpolation",
                title: "Avoid FromSqlRaw with interpolated strings",
                category: "Security",
                domain: "Raw SQL & Security",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AvoidFromSqlRawWithInterpolationAnalyzer",
                fixerTypeName: "AvoidFromSqlRawWithInterpolationFixer",
                documentationPath: "docs/LC018_AvoidFromSqlRawWithInterpolation.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC018_AvoidFromSqlRawWithInterpolation/AvoidFromSqlRawWithInterpolationSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/RawSqlAndSecurity/LC018_AvoidFromSqlRawWithInterpolation",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC019",
                slug: "LC019_ConditionalInclude",
                title: "Conditional Include Expression",
                category: "Correctness",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "ConditionalIncludeAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC019_ConditionalInclude.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC019_ConditionalInclude/ConditionalIncludeSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC019_ConditionalInclude",
                hasCodeFix: false,
                noCodeFixRationale: "No generally correct code fix: callers must choose between splitting queries, reshaping projections, or removing the conditional include path."),
            new RuleCatalogEntry(
                id: "LC020",
                slug: "LC020_StringContainsWithComparison",
                title: "Avoid untranslatable string comparison overloads",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "StringContainsWithComparisonAnalyzer",
                fixerTypeName: "StringContainsWithComparisonFixer",
                documentationPath: "docs/LC020_StringContainsWithComparison.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC020_StringContainsWithComparison/StringContainsWithComparisonSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC020_StringContainsWithComparison",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC021",
                slug: "LC021_AvoidIgnoreQueryFilters",
                title: "Avoid IgnoreQueryFilters",
                category: "Security",
                domain: "Raw SQL & Security",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AvoidIgnoreQueryFiltersAnalyzer",
                fixerTypeName: "AvoidIgnoreQueryFiltersFixer",
                documentationPath: "docs/LC021_AvoidIgnoreQueryFilters.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC021_AvoidIgnoreQueryFilters/AvoidIgnoreQueryFiltersSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/RawSqlAndSecurity/LC021_AvoidIgnoreQueryFilters",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC022",
                slug: "LC022_ToListInSelectProjection",
                title: "Nested collection materialization inside projection",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "ToListInSelectProjectionAnalyzer",
                fixerTypeName: "ToListInSelectProjectionFixer",
                documentationPath: "docs/LC022_ToListInSelectProjection.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC022_ToListInSelectProjection/ToListInSelectProjectionSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC022_ToListInSelectProjection",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC023",
                slug: "LC023_FindInsteadOfFirstOrDefault",
                title: "Use Find/FindAsync for primary key lookups",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "FindInsteadOfFirstOrDefaultAnalyzer",
                fixerTypeName: "FindInsteadOfFirstOrDefaultFixer",
                documentationPath: "docs/LC023_FindInsteadOfFirstOrDefault.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC023_FindInsteadOfFirstOrDefault/FindInsteadOfFirstOrDefaultSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC023_FindInsteadOfFirstOrDefault",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC024",
                slug: "LC024_GroupByNonTranslatable",
                title: "GroupBy with Non-Translatable Projection",
                category: "Performance",
                domain: "Query Shape & Translation",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "GroupByNonTranslatableAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC024_GroupByNonTranslatable.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC024_GroupByNonTranslatable/GroupByNonTranslatableSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/QueryShapeAndTranslation/LC024_GroupByNonTranslatable",
                hasCodeFix: false,
                noCodeFixRationale: "No safe one-click fix: the correct rewrite depends on whether the query should aggregate on the server, project earlier, or materialize intentionally before performing complex grouping in memory."),
            new RuleCatalogEntry(
                id: "LC025",
                slug: "LC025_AsNoTrackingWithUpdate",
                title: "Avoid AsNoTracking with Update/Remove",
                category: "Reliability",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "AsNoTrackingWithUpdateAnalyzer",
                fixerTypeName: "AsNoTrackingWithUpdateFixer",
                documentationPath: "docs/LC025_AsNoTrackingWithUpdate.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC025_AsNoTrackingWithUpdate/AsNoTrackingWithUpdateSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC025_AsNoTrackingWithUpdate",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC026",
                slug: "LC026_MissingCancellationToken",
                title: "Missing CancellationToken in async call",
                category: "Reliability",
                domain: "Execution & Async",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MissingCancellationTokenAnalyzer",
                fixerTypeName: "MissingCancellationTokenFixer",
                documentationPath: "docs/LC026_MissingCancellationToken.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC026_MissingCancellationToken/MissingCancellationTokenSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ExecutionAndAsync/LC026_MissingCancellationToken",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC027",
                slug: "LC027_MissingExplicitForeignKey",
                title: "Missing Explicit Foreign Key Property",
                category: "Design",
                domain: "Schema & Modeling",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "MissingExplicitForeignKeyAnalyzer",
                fixerTypeName: "MissingExplicitForeignKeyFixer",
                documentationPath: "docs/LC027_MissingExplicitForeignKey.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC027_MissingExplicitForeignKey/MissingExplicitForeignKeySample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/SchemaAndModeling/LC027_MissingExplicitForeignKey",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC028",
                slug: "LC028_DeepThenInclude",
                title: "Deep ThenInclude Chain",
                category: "Performance",
                domain: "Loading & Includes",
                severity: DiagnosticSeverity.Warning,
                analyzerTypeName: "DeepThenIncludeAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC028_DeepThenInclude.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC028_DeepThenInclude/DeepThenIncludeSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/LoadingAndIncludes/LC028_DeepThenInclude",
                hasCodeFix: false,
                noCodeFixRationale: "No safe automated fix: reducing eager-loading depth requires a domain-specific decision about projections, split queries, or alternate loading patterns."),
            new RuleCatalogEntry(
                id: "LC029",
                slug: "LC029_RedundantIdentitySelect",
                title: "Redundant identity Select",
                category: "Performance",
                domain: "Materialization & Projection",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "RedundantIdentitySelectAnalyzer",
                fixerTypeName: "RedundantIdentitySelectFixer",
                documentationPath: "docs/LC029_RedundantIdentitySelect.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC029_RedundantIdentitySelect/RedundantIdentitySelectSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/MaterializationAndProjection/LC029_RedundantIdentitySelect",
                hasCodeFix: true,
                noCodeFixRationale: null),
            new RuleCatalogEntry(
                id: "LC030",
                slug: "LC030_DbContextInSingleton",
                title: "Potential DbContext lifetime mismatch",
                category: "Architecture",
                domain: "Change Tracking & Context Lifetime",
                severity: DiagnosticSeverity.Info,
                analyzerTypeName: "DbContextInSingletonAnalyzer",
                fixerTypeName: null,
                documentationPath: "docs/LC030_DbContextInSingleton.md",
                samplePath: "samples/LinqContraband.Sample/Samples/LC030_DbContextInSingleton/DbContextInSingletonSample.cs",
                analyzerSourcePath: "src/LinqContraband/Analyzers/ChangeTrackingAndContextLifetime/LC030_DbContextInSingleton",
                hasCodeFix: false,
                noCodeFixRationale: "No safe automated fix: correcting DbContext lifetime depends on the service registration, ownership model, and whether to use a factory or a scoped component.")
        );
    }
}
